server:
  port: "8080"

db:
  host: "localhost"
  port: "5432"
  user: "your_db_user"
  password: "your_db_password"
  name: "your_db_name"

jwt:
  secret: "your-jwt-secret"
  expiration: 60 # JWT token expiration time in minutes

auth:
  enabled: false