// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';

export function AddRecentDataDirectory(arg1:string):Promise<void>;

export function CleanupOldVersions(arg1:string,arg2:number):Promise<void>;

export function DeletePromptDefinition(arg1:string):Promise<void>;

export function FindPromptDefinitionByID(arg1:string):Promise<main.PromptDefinition>;

export function GetCurrentDirectory():Promise<string>;

export function GetDataDirectory():Promise<string>;

export function GetInitialLLMSettings():Promise<Record<string, string>>;

export function GetPromptVariantsForModel(arg1:string):Promise<Array<main.PromptVariant>>;

export function GetRecentDataDirectories():Promise<Array<string>>;

export function GetResolvedProsePrompt(arg1:string,arg2:string):Promise<string>;

export function GetStorageStats():Promise<storage.StorageStats>;

export function HandleFileDrop(arg1:Array<string>):Promise<void>;

export function LoadPromptDefinitions():Promise<Array<main.PromptDefinition>>;

export function LogInfo(arg1:string):Promise<void>;

export function ProcessFolder(arg1:string,arg2:Record<string, any>):Promise<Array<string>>;

export function ReadCharactersFile():Promise<string>;

export function ReadCodexFile():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReadLLMSettingsFile():Promise<string>;

export function ReadLocationsFile():Promise<string>;

export function ReadPromptDefinitionsFile():Promise<string>;

export function ReadPromptsFile():Promise<string>;

export function ReadProsePromptsFile():Promise<string>;

export function ReadRulesFile():Promise<string>;

export function ReadRulessFile():Promise<string>;

export function ReadSampleChaptersFile():Promise<string>;

export function ReadSettingsFile():Promise<string>;

export function ReadTaskTypesFile():Promise<string>;

export function SavePromptDefinitions(arg1:Array<main.PromptDefinition>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SetDataDirectory(arg1:string):Promise<void>;

export function UpdatePromptDefinition(arg1:main.PromptDefinition):Promise<void>;

export function ValidateDataDirectory():Promise<void>;

export function ValidateDataDirectoryPath(arg1:string):Promise<void>;

export function WriteCharactersFile(arg1:string):Promise<void>;

export function WriteCodexFile(arg1:string):Promise<void>;

export function WriteLLMSettingsFile(arg1:string):Promise<void>;

export function WriteLocationsFile(arg1:string):Promise<void>;

export function WritePromptDefinitionsFile(arg1:string):Promise<void>;

export function WritePromptsFile(arg1:string):Promise<void>;

export function WriteProsePromptsFile(arg1:string):Promise<void>;

export function WriteRulesFile(arg1:string):Promise<void>;

export function WriteRulessFile(arg1:string):Promise<void>;

export function WriteSampleChaptersFile(arg1:string):Promise<void>;

export function WriteSettingsFile(arg1:string):Promise<void>;

export function WriteTaskTypesFile(arg1:string):Promise<void>;
