// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentDirectory():Promise<string>;

export function HandleFileDrop(arg1:Array<string>):Promise<void>;

export function LogInfo(arg1:string):Promise<void>;

export function ProcessFolder(arg1:string,arg2:Record<string, any>):Promise<Array<string>>;

export function ReadCharactersFile():Promise<string>;

export function ReadCodexFile():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReadLocationsFile():Promise<string>;

export function ReadRulesFile():Promise<string>;

export function ReadRulessFile():Promise<string>;

export function ReadSampleChaptersFile():Promise<string>;

export function ReadSettingsFile():Promise<string>;

export function ReadTaskTypesFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function WriteCharactersFile(arg1:string):Promise<void>;

export function WriteCodexFile(arg1:string):Promise<void>;

export function WriteLocationsFile(arg1:string):Promise<void>;

export function WriteRulesFile(arg1:string):Promise<void>;

export function WriteRulessFile(arg1:string):Promise<void>;

export function WriteSampleChaptersFile(arg1:string):Promise<void>;

export function WriteSettingsFile(arg1:string):Promise<void>;

export function WriteTaskTypesFile(arg1:string):Promise<void>;
