// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentDataDirectory(arg1) {
  return window['go']['main']['App']['AddRecentDataDirectory'](arg1);
}

export function CleanupOldVersions(arg1, arg2) {
  return window['go']['main']['App']['CleanupOldVersions'](arg1, arg2);
}

export function ConvertMCPCharacterToServer(arg1) {
  return window['go']['main']['App']['ConvertMCPCharacterToServer'](arg1);
}

export function ConvertServerCharacterToMCP(arg1) {
  return window['go']['main']['App']['ConvertServerCharacterToMCP'](arg1);
}

export function DeletePromptDefinition(arg1) {
  return window['go']['main']['App']['DeletePromptDefinition'](arg1);
}

export function FindPromptDefinitionByID(arg1) {
  return window['go']['main']['App']['FindPromptDefinitionByID'](arg1);
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetDataDirectory() {
  return window['go']['main']['App']['GetDataDirectory']();
}

export function GetDataDirectoryInfo() {
  return window['go']['main']['App']['GetDataDirectoryInfo']();
}

export function GetInitialLLMSettings() {
  return window['go']['main']['App']['GetInitialLLMSettings']();
}

export function GetPromptVariantsForModel(arg1) {
  return window['go']['main']['App']['GetPromptVariantsForModel'](arg1);
}

export function GetRecentDataDirectories() {
  return window['go']['main']['App']['GetRecentDataDirectories']();
}

export function GetResolvedProsePrompt(arg1, arg2) {
  return window['go']['main']['App']['GetResolvedProsePrompt'](arg1, arg2);
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function HandleFileDrop(arg1) {
  return window['go']['main']['App']['HandleFileDrop'](arg1);
}

export function LoadPromptDefinitions() {
  return window['go']['main']['App']['LoadPromptDefinitions']();
}

export function LogInfo(arg1) {
  return window['go']['main']['App']['LogInfo'](arg1);
}

export function ProcessFolder(arg1, arg2) {
  return window['go']['main']['App']['ProcessFolder'](arg1, arg2);
}

export function ReadCharactersFile() {
  return window['go']['main']['App']['ReadCharactersFile']();
}

export function ReadCodexFile() {
  return window['go']['main']['App']['ReadCodexFile']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ReadLLMSettingsFile() {
  return window['go']['main']['App']['ReadLLMSettingsFile']();
}

export function ReadLocationsFile() {
  return window['go']['main']['App']['ReadLocationsFile']();
}

export function ReadPromptDefinitionsFile() {
  return window['go']['main']['App']['ReadPromptDefinitionsFile']();
}

export function ReadPromptsFile() {
  return window['go']['main']['App']['ReadPromptsFile']();
}

export function ReadProsePromptsFile() {
  return window['go']['main']['App']['ReadProsePromptsFile']();
}

export function ReadRulesFile() {
  return window['go']['main']['App']['ReadRulesFile']();
}

export function ReadRulessFile() {
  return window['go']['main']['App']['ReadRulessFile']();
}

export function ReadSampleChaptersFile() {
  return window['go']['main']['App']['ReadSampleChaptersFile']();
}

export function ReadSettingsFile() {
  return window['go']['main']['App']['ReadSettingsFile']();
}

export function ReadTaskTypesFile() {
  return window['go']['main']['App']['ReadTaskTypesFile']();
}

export function SavePromptDefinitions(arg1) {
  return window['go']['main']['App']['SavePromptDefinitions'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetDataDirectory(arg1) {
  return window['go']['main']['App']['SetDataDirectory'](arg1);
}

export function SetDataDirectoryMCP(arg1) {
  return window['go']['main']['App']['SetDataDirectoryMCP'](arg1);
}

export function UpdatePromptDefinition(arg1) {
  return window['go']['main']['App']['UpdatePromptDefinition'](arg1);
}

export function ValidateDataDirectory() {
  return window['go']['main']['App']['ValidateDataDirectory']();
}

export function ValidateDataDirectoryPath(arg1) {
  return window['go']['main']['App']['ValidateDataDirectoryPath'](arg1);
}

export function WriteCharactersFile(arg1) {
  return window['go']['main']['App']['WriteCharactersFile'](arg1);
}

export function WriteCodexFile(arg1) {
  return window['go']['main']['App']['WriteCodexFile'](arg1);
}

export function WriteLLMSettingsFile(arg1) {
  return window['go']['main']['App']['WriteLLMSettingsFile'](arg1);
}

export function WriteLocationsFile(arg1) {
  return window['go']['main']['App']['WriteLocationsFile'](arg1);
}

export function WritePromptDefinitionsFile(arg1) {
  return window['go']['main']['App']['WritePromptDefinitionsFile'](arg1);
}

export function WritePromptsFile(arg1) {
  return window['go']['main']['App']['WritePromptsFile'](arg1);
}

export function WriteProsePromptsFile(arg1) {
  return window['go']['main']['App']['WriteProsePromptsFile'](arg1);
}

export function WriteRulesFile(arg1) {
  return window['go']['main']['App']['WriteRulesFile'](arg1);
}

export function WriteRulessFile(arg1) {
  return window['go']['main']['App']['WriteRulessFile'](arg1);
}

export function WriteSampleChaptersFile(arg1) {
  return window['go']['main']['App']['WriteSampleChaptersFile'](arg1);
}

export function WriteSettingsFile(arg1) {
  return window['go']['main']['App']['WriteSettingsFile'](arg1);
}

export function WriteTaskTypesFile(arg1) {
  return window['go']['main']['App']['WriteTaskTypesFile'](arg1);
}
