// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleFileDrop(arg1:Array<string>):Promise<void>;

export function LogInfo(arg1:string):Promise<void>;

export function ProcessFolder(arg1:string,arg2:{[key: string]: any}):Promise<Array<string>>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReadRulessFile():Promise<string>;

export function ReadSettingsFile():Promise<string>;

export function ReadTaskTypesFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function WriteRulessFile(arg1:string):Promise<void>;

export function WriteSettingsFile(arg1:string):Promise<void>;

export function WriteTaskTypesFile(arg1:string):Promise<void>;
